name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-docker-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build server image
        run: docker build -t mfp-server:latest ./server

      - name: Build client image
        run: docker build -t mfp-client:latest ./client